platform :ios, '9.0'
use_frameworks!

pod 'SwiftBehave', :path => "../SwiftBehave.podspec"

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['FRAMEWORK_SEARCH_PATHS'] = [ '$(PLATFORM_DIR)/Developer/Library/Frameworks' ]
        end
    end
end
